"""
Django settings for stray_animal_management project.

Generated by 'django-admin startproject' using Django 5.2.11.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os

# ============================================================
# BASE DIRECTORY
# ============================================================
BASE_DIR = Path(__file__).resolve().parent.parent


# ============================================================
# SECURITY SETTINGS
# ============================================================
SECRET_KEY = 'django-insecure-pawzen-2026-change-this-in-production-xyz123abc456def789'

DEBUG = True  # Change to False when deploying to production

ALLOWED_HOSTS = [
    'localhost',
    '127.0.0.1',
    'pawzen.pythonanywhere.com',  # Add your hosting domain here
    'www.pawzen.com',             # Add your custom domain here
]


# ============================================================
# INSTALLED APPS
# ============================================================
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'stray_animals',   # Your PawZen app
]


# ============================================================
# MIDDLEWARE (ORDER IS IMPORTANT - DO NOT CHANGE ORDER)
# ============================================================
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]


# ============================================================
# URL CONFIGURATION
# ============================================================
ROOT_URLCONF = 'stray_animal_management.urls'


# ============================================================
# TEMPLATES
# ============================================================
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'stray_animal_management' / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]


# ============================================================
# WSGI APPLICATION
# ============================================================
WSGI_APPLICATION = 'stray_animal_management.wsgi.application'


# ============================================================
# DATABASE - MySQL
# ============================================================
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'pawzen_db',
        'USER': 'pawzen_user',
        'PASSWORD': 'Pawzen2026',
        'HOST': 'localhost',
        'PORT': '3306',
        'OPTIONS': {
            'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
            'charset': 'utf8mb4',
        },
        'CONN_MAX_AGE': 60,
    }
}


# ============================================================
# CUSTOM USER MODEL
# ============================================================
AUTH_USER_MODEL = 'stray_animals.User'


# ============================================================
# PASSWORD VALIDATION
# ============================================================
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {
            'min_length': 8,
        },
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# ============================================================
# INTERNATIONALIZATION
# ============================================================
LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kolkata'

USE_I18N = True

USE_TZ = True


# ============================================================
# STATIC FILES
# ============================================================
STATIC_URL = '/static/'

STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

STATIC_ROOT = BASE_DIR / 'staticfiles'


# ============================================================
# MEDIA FILES
# ============================================================
MEDIA_URL = '/media/'

MEDIA_ROOT = BASE_DIR / 'media'


# ============================================================
# DEFAULT PRIMARY KEY FIELD TYPE
# ============================================================
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# ============================================================
# LOGIN / LOGOUT URLS
# ============================================================
LOGIN_URL = '/'
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/'


# ============================================================
# SESSION SETTINGS (Security)
# ============================================================
SESSION_COOKIE_AGE = 3600               # Session expires in 1 hour (3600 seconds)
SESSION_EXPIRE_AT_BROWSER_CLOSE = True  # Expire session when browser closes
SESSION_SAVE_EVERY_REQUEST = True       # Refresh session timer on every request
SESSION_COOKIE_HTTPONLY = True          # Session cookie not accessible via JavaScript
SESSION_COOKIE_SAMESITE = 'Lax'        # Prevent CSRF via session cookie


# ============================================================
# CSRF SETTINGS (Security)
# ============================================================
CSRF_COOKIE_HTTPONLY = False            # Must be False for Django forms to work
CSRF_COOKIE_SAMESITE = 'Lax'           # Prevent cross-site request forgery
CSRF_TRUSTED_ORIGINS = [
    'http://localhost:8000',
    'http://127.0.0.1:8000',
    'https://pawzen.pythonanywhere.com',
    'https://www.pawzen.com',
]


# ============================================================
# MESSAGES FRAMEWORK (Bootstrap Alert Integration)
# ============================================================
from django.contrib.messages import constants as messages

MESSAGE_TAGS = {
    messages.DEBUG:   'debug',
    messages.INFO:    'info',
    messages.SUCCESS: 'success',
    messages.WARNING: 'warning',
    messages.ERROR:   'danger',
}


# ============================================================
# EMAIL CONFIGURATION (Gmail SMTP)
# ============================================================
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'adiprasanth200510@gmail.com'
EMAIL_HOST_PASSWORD = 'your-gmail-app-password-here'  # Generate from Google Account
DEFAULT_FROM_EMAIL = 'PawZen <adiprasanth200510@gmail.com>'
SERVER_EMAIL = 'adiprasanth200510@gmail.com'


# ============================================================
# SECURITY HEADERS
# ============================================================
SECURE_BROWSER_XSS_FILTER = True       # Enable XSS filtering
SECURE_CONTENT_TYPE_NOSNIFF = True     # Prevent MIME type sniffing
X_FRAME_OPTIONS = 'DENY'              # Prevent clickjacking


# ============================================================
# LOGGING (Track errors and warnings)
# ============================================================
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'file': {
            'level': 'ERROR',
            'class': 'logging.FileHandler',
            'filename': BASE_DIR / 'pawzen_errors.log',
            'formatter': 'verbose',
        },
        'console': {
            'level': 'DEBUG',
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'WARNING',
    },
    'loggers': {
        'django': {
            'handlers': ['file', 'console'],
            'level': 'ERROR',
            'propagate': False,
        },
        'stray_animals': {
            'handlers': ['file', 'console'],
            'level': 'DEBUG',
            'propagate': False,
        },
    },
}

