# Generated by Django 4.2.7 on 2026-02-24 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stray_animals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='strayanimalreport',
            name='care_center_notified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Username can contain letters, numbers, spaces, and @/./+/-/_ characters.', max_length=150, unique=True),
        ),
    ]
