# Generated by Django 4.2.7 on 2026-03-01 06:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stray_animals', '0002_strayanimalreport_care_center_notified_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='veterinaryconsultation',
            name='consultation_date',
        ),
        migrations.RemoveField(
            model_name='veterinaryconsultation',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='veterinaryconsultation',
            name='animal_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='veterinaryconsultation',
            name='animal_type',
            field=models.CharField(blank=True, choices=[('Dog', 'Dog'), ('Cat', 'Cat')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='veterinaryconsultation',
            name='animal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consultations', to='stray_animals.strayanimalreport'),
        ),
        migrations.AlterField(
            model_name='veterinaryconsultation',
            name='veterinarian',
            field=models.ForeignKey(limit_choices_to={'user_type': 'veterinarian'}, on_delete=django.db.models.deletion.CASCADE, related_name='consultations_as_vet', to=settings.AUTH_USER_MODEL),
        ),
    ]
