# Generated by Django 4.2.7 on 2026-03-01 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stray_animals', '0003_remove_veterinaryconsultation_consultation_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='animaladoption',
            name='notification_seen',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='strayanimalreport',
            name='notification_seen',
            field=models.BooleanField(default=False),
        ),
    ]
