# Generated by Django 4.2.7 on 2026-03-01 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stray_animals', '0004_animaladoption_notification_seen_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='strayanimalreport',
            name='healthy_image',
            field=models.ImageField(blank=True, null=True, upload_to='healthy_animals/'),
        ),
        migrations.AddField(
            model_name='strayanimalreport',
            name='reported_image',
            field=models.ImageField(blank=True, null=True, upload_to='reported_animals/'),
        ),
        migrations.AddField(
            model_name='veterinaryconsultation',
            name='consultation_image',
            field=models.ImageField(blank=True, null=True, upload_to='consultation_images/'),
        ),
    ]
